source 'https://github.com/CocoaPods/Specs.git'
# use_frameworks!

target 'DSLibCore', :exclusive => true do
  pod "DSLibCore", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end

#target 'DSLibCorePlayground', :exclusive => true do
#  pod "DSLibCore", :path => "../"
#end
